Repository rpm-software-management/ci-dnf-stack, pull requests merged in 2023-06, with the labels that each got.

#1305 CLI now returns error exit code after RPM transaction error
  dnf-behave-tests/dnf/install-file-conflicts.feature
Labels: ready for review

#1282 New tests for leaves and show-leaves plugins
  dnf-behave-tests/dnf/plugins-core/leaves.feature
  dnf-behave-tests/dnf/steps/cmd.py
  dnf-behave-tests/requirements.spec
Labels: ready for review

#1293 Tests for "proxy=" and "proxy=_none_" (RhBug:1680272, RhBug:2155713)
  dnf-behave-tests/dnf/microdnf/proxy-empty-none.feature
  dnf-behave-tests/dnf/proxy-empty-none.feature
Labels: ready for review, stale

#1316 Tests for "proxy=" and "proxy=_none_" (RhBug:1680272, RhBug:2155713)
  dnf-behave-tests/dnf/microdnf/proxy-empty-none.feature
  dnf-behave-tests/dnf/proxy-empty-none.feature
Labels: ready for review

#1322 Tests for changelog --since
  dnf-behave-tests/dnf/plugins-core/changelog.feature
  dnf-behave-tests/fixtures/specs/dnf-ci-changelog/pkg-with-changelogs-1.0-3.spec
Labels: ready for review

#1315 API: add more scenarios for PackageQuery
  dnf-behave-tests/dnf/api/package-query.feature
Labels: ready for review

#1264 downgrade.feature: update dnf4 scenarios for dnf5
  dnf-behave-tests/dnf/downgrade.feature
  dnf-behave-tests/dnf/shell-downgrade.feature
Labels: blocked
